### PR TITLE
Displaying warning in Settings if RSS feed is W3C invalid

### PR DESCRIPTION
**Pull request by stulees**
- Updating translations dependency
- Adding warning paragraph below URL Field which includes a configured link to view W3C validator page detailing all errors of the feed
- Adding feed validation service which uses our Proxy (CORS) and the W3C Feed Validator API to determine validity of RSS feed provided
- Using `xmlToJSON` to parse the XML response
- Validation check is done on loss of focus of URL Field and when previously saved settings are restored
- Unit tests added for `svc-feed-validation.js` including mock XML and JSON
- e2e tests added

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks. 

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=bc041e26-0e67-414f-8c49-37e3a0a1343e?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
