### PR TITLE
Add "Show Timestamp" setting [stage-3]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Correct dist files now committed. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by rodrigopavezi** [comment]
@donnapep @stulees I have added the font setting for the timestamp. Please review.

Presentation here: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=194e33f9-1293-441f-963a-4e7462fa8fe6?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

cheers

**Comment by stulees** [comment]
@rodrigopavezi :+1:

**Pull request merged**
