### PR TITLE
Refresh scroller when RSS feed updates

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review the 3rd commit. The others are from the previous PR. Thx.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Also, the last 2 commits need reviewing. Thx!

**Comment by stulees** [comment]
@donnapep Looks like there are conflicts to resolve and rebase

**Comment by donnapep** [comment]
@stulees I know, but they're from the previous PR. I'll rebase after that one ships.

**Comment by donnapep** [comment]
@stulees This PR has been rebased now. Thx.

**Comment by stulees** [comment]
@donnapep :+1: looks good but confused by the commit title as I think it's also a previous commit title ...

**Pull request merged**
