### PR TITLE
Feature/show title

### PR DESCRIPTION
**Pull request by donnapep**
* Add "Show Title" functionality.
* Added in missing tests.
* Fixed issue with headline not being removed from DOM.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep FYI, I think you're committing an older version of `rise-rss`. The diff it's showing is removing the changes @rodrigopavezi had implemented in latest version. Seems like you needed a fresh bower install.

**Comment by rodrigopavezi** [comment]
@stulees good catch, thank you for that. cheers

**Pull request merged**
