### PR TITLE
Added rss widget settings for first release

### PR DESCRIPTION
**Pull request by rodrigopavezi**
- RSS Url
- Title Style
- Story Style

@donnapep @stulees please review. 

Presentation here:

http://rva.risevision.com/#/PRESENTATION_MANAGE/id=4e84b8c9-080c-4fb7-889c-81ed365cf930?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi You'll need to include tinymce files for distributing to our vendor folder. See Time & Date here for which files - https://github.com/Rise-Vision/widget-time-date/blob/master/gulpfile.js#L32-L35

**Comment by rodrigopavezi** [comment]
@stulees added, thanks for catching that.

**Comment by stulees** [comment]
@rodrigopavezi You'll need to build again so you can commit those vendor tinymce files, cheers

**Comment by rodrigopavezi** [comment]
@stulees sorry for that. I built but it did not add the files to git. Now it should be there. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good :+1:

**Pull request merged**
