### PR TITLE
Apply default font settings to match layout images [stage-4]

### PR DESCRIPTION
**Pull request by stulees**
- settings controller now applying specific font settings configurations to match the layout images
- tests revised

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit only, previous commits are from another PR that I branched off of. I will rebase this PR before merging once approved and validated. Thanks

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=ff1e3aa3-4fe5-488d-a989-ddd815209427?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1:  cheers

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
