### PR TITLE
Add Bower resolution [stage-1]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep Can the dependency be changed to `^0.13.0` instead of the resolution?

**Comment by stulees** [comment]
@donnapep :+1:  I've noticed I need to resolve in widget-settings-ui-components repo too. Once I create a new release of that repo (transition-setting component), we'll be able to remove this resolution in RSS when we point to the latest widget-settings-ui-components.

**Pull request merged**
