### PR TITLE
Display and Scroll

### PR DESCRIPTION
**Pull request by stulees**
- 4x1 template added
- configuring and loading images
- formatting content to template
- displaying items
- truncating items with dotdotdot
- implementing auto scroll

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Added a couple of comments.

**Comment by stulees** [comment]
@donnapep Made changes to your two comments, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
