### PR TITLE
Build/test infrastructure, base files, initial tests

### PR DESCRIPTION
**Pull request by stulees**
- editor config files
- bower and npm package files defined
- gulp file defined with necessary tasks
- CCI
- config files defined
- settings HTML, controller, and app
- widget HTML and base JS files
- settings e2e tests
- dist/ added

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Did you create that Analytics ID? I don't see one with that ID listed over there.

**Comment by stulees** [comment]
@donnapep Glad you caught that, I was anticipating that id to be the new one but then Alan just reminded me that we're going to use segment.io for tracking which is part of this Widget work scope. I've now removed the analytics file from the source, rebased, review again. Thanks!

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
