### PR TITLE
Widget implementation of first release

### PR DESCRIPTION
**Pull request by stulees**
- Loading rss feed, displaying one feed item at a time (no transition fade) every 10 seconds
- Displaying headline and story for each rss item and applying font styling accordingly
- Truncating rss item content with ellipsis to fit in placeholder size
- Refreshing feed every 60 seconds and only updating content if feed has changed
- Integration tests

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=c4952e73-4d50-4e39-b068-0d8a33b73a13?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit, thanks.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Latest commit fixes the xml version bug, please review, thanks

**Comment by donnapep** [comment]
@stulees Good stuff. :+1:

**Pull request merged**
