### PR TITLE
Fixes #104 - Images not displaying for articles with enclosures tag

### LINKED ISSUE #104: Widget not showing images
**What's happening?**
On some feeds (at least one example) the images are not displaying correctly.

**How to recreate**
1. Created a RSS widget and used the url http://feeds.feedburner.com/foxnews/latest
2. Tried all layout options
3. The feed was not showing images (screenshot attached)

got

Expected images like this example RSS reader

expected

### PR DESCRIPTION
**Pull request by jungeunyoon**
Closes #104

### CODE REVIEW

**Comment by jungeunyoon** [comment]
@stulees Please review, thanks. 

Went ahead and modified one of the test feeds `test/data/json-atom1.js` to handle cases where enclosure tags are invalid (enclosure tag exists but is empty). We test against valid enclosure tags in the second item in the same feed and in the other feeds. 

Decided against adding test cases for invalid image file type and unprovided url in enclosure tag because we don't currently have a fallback in place other than grabbing straight from image tag but that seems sufficient. We could have a default image as a fallback but it would be very low in priority and pretty unnecessary.

**Comment by stulees** [comment]
@jungeunyoon Curious, are you aware of our [widget-preview](https://github.com/Rise-Vision/widget-preview) app to test widgets locally? If so, have you tested this fix locally? 

Also, we always test widgets with a staged a version of the widget to use in a presentation. The widget build is configured to deploy a staged version to a specific bucket folder on Amazon S3. When this gets merged, the master build deploys to a specific production bucket folder on Amazon S3. 

@rodrigopavezi Since you're moving over to Creative with @jungeunyoon , it might be best for you to take her through the above in regards to:

- local widget testing with widget-preview app
- Amazon S3 access and our widget bucket folder directories
- widget build 
- how to test the staged version in editor -> preview -> display 

Or perhaps a hangout with both of us is required? Thoughts?

**Comment by jungeunyoon** [comment]
@stulees @rodrigopavezi Yes, it's been tested through Widget Preview already.

Definitely going to need some help with the staged version testing.

**Comment by jungeunyoon** [comment]
@rodrigopavezi If you wouldn't mind doing a final review, thanks!

**Pull request merged**
