### PR TITLE
Adding support for vertical auto scrolling

### PR DESCRIPTION
**Pull request by stulees**
- bower dependency updates
- adding `transition-setting` to settings
- adding auto-scroll dependencies to widget HTML
- refactoring `content.js` and separating transition specific code to new `transition-no-scroll.js` and `transition-vertical-scroll.js` modules
- `content.js` module can get width and height from params, doesn't need prefs passed to it
- revised and fixed existing test coverage
- added integration tests for vertical scrolling

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees Looks good to me. :+1:

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees loos good :+1: cheers

**Pull request merged**
