### PR TITLE
Adding support for items to show

### PR DESCRIPTION
**Pull request by stulees**
- Items to show now configurable in settings, default value is 2
- Implemented in widget
- Integration tests revised and added

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks.

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=f9bbca66-7720-4f0f-9497-a8a36e362a54?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees shouldn't it come side by side with the Max Items in Queue? cheers

**Comment by stulees** [comment]
@rodrigopavezi Good catch, have now corrected.

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Pull request merged**
